Lesson 3
UWPCE-PythonCert-ClassRepos/Python210_Fall2019 pull request #34
Opened 2019-11-05 04:16 UTC by Pizzabagels

Merging lesson 3 mailroom homeworks

2019-11-05 23:14 UTC, majstorpoki requested changes
Did you accomplish file write functionality in pt 2?

2019-11-05 23:14 UTC, majstorpoki commented on students/Tommy Aguilu/mailroom_part2.py
> +        sentinal = False
Intelligent and neat

2019-11-05 23:14 UTC, majstorpoki commented on students/Tommy Aguilu/mailroom_part2.py
> +    x.append((sum(value)/len(value)).__round__()) #avg donations
nice

2019-11-05 23:14 UTC, majstorpoki commented on students/Tommy Aguilu/mailroom_part2.py
> +    x = []
Nice, list of lists for processed donors

2019-11-05 23:14 UTC, majstorpoki commented on students/Tommy Aguilu/mailroom_part2.py
> +### Author - Tommy Aguilu
Update mailroom with file writing.
Goal: Write a full set of letters to all donors to individual files on disk.

Where is this accomplished?

2019-11-06 00:21 UTC, Pizzabagels commented
Hey Dr. Pokrajac,

Yes writing a full set of letters based on the donor list is in the
function send_many. In that function it writes a file named after the key
of the value in the list and then writes a string with the key and last
value in the list inserted into a predetermined sentence in to the file it
just created. This is found on lines 27-34.


    for k,v  in donor_raw.items():
        with open(k, "w") as f:
            length = (len(v)-1)
            f.write(("thank you {} for your most recent donation of
{}".format(k, v[length])))
            f.close()


On Tue, Nov 5, 2019 at 3:14 PM majstorpoki <notifications@github.com> wrote:

> *@majstorpoki* requested changes on this pull request.
>
> Did you accomplish file write functionality in pt 2?
> ------------------------------
>
> In students/Tommy Aguilu/mailroom_part2.py
> <https://github.com/UWPCE-PythonCert-ClassRepos/Python210_Fall2019/pull/34#discussion_r342841343>
> :
>
> > +    elif choice == str(2):
> +        donor_list(donor_raw)
> +        donor_choice = input("Which donor would you like to write a thank you to? (type all if you would like to send it a letter to all) ")
> +        if donor_choice in donor_raw:
> +            donor_letter(donor_raw,donor_choice)
> +        if donor_choice == "all":
> +            send_many(donor_raw)
> +        else:
> +            donation_list = []
> +            donation = input("Donor not found in list please specify how donation amount")
> +            donation_list.append(donation)
> +            donor_raw.update({donor_choice : donation_list})
> +            donor_letter(donor_raw,donor_choice)
> +    elif choice == str(3):
> +        print("closing out")
> +        sentinal = False
>
> Intelligent and neat
> ------------------------------
>
> In students/Tommy Aguilu/mailroom_part2.py
> <https://github.com/UWPCE-PythonCert-ClassRepos/Python210_Fall2019/pull/34#discussion_r342841514>
> :
>
> > +def send_many(donor_raw):
> +    for k in donor_raw:
> +        for k,v  in donor_raw.items():
> +            with open(k, "w") as f:
> +                length = (len(v)-1)
> +                f.write(("thank you {} for your most recent donation of {}".format(k, v[length])))
> +                f.close()
> +    print("letters sent!")
> +
> +
> +for key, value in donor_raw.items():
> +    x = []
> +    x.append(key)
> +    x.append(sum(value)) #total donations
> +    x.append(len(value)) #number of donations
> +    x.append((sum(value)/len(value)).__round__()) #avg donations
>
> nice
> ------------------------------
>
> In students/Tommy Aguilu/mailroom_part2.py
> <https://github.com/UWPCE-PythonCert-ClassRepos/Python210_Fall2019/pull/34#discussion_r342841619>
> :
>
> > +    donations = (donor_raw[donor_choice])
> +    donations_output = donations[-1]
> +    print("thank you {} for your most recent donation of {}".format(donor_choice, donations_output))
> +
> +def send_many(donor_raw):
> +    for k in donor_raw:
> +        for k,v  in donor_raw.items():
> +            with open(k, "w") as f:
> +                length = (len(v)-1)
> +                f.write(("thank you {} for your most recent donation of {}".format(k, v[length])))
> +                f.close()
> +    print("letters sent!")
> +
> +
> +for key, value in donor_raw.items():
> +    x = []
>
> Nice, list of lists for processed donors
> ------------------------------
>
> In students/Tommy Aguilu/mailroom_part2.py
> <https://github.com/UWPCE-PythonCert-ClassRepos/Python210_Fall2019/pull/34#discussion_r342846400>
> :
>
> > @@ -0,0 +1,65 @@
> +### Author - Tommy Aguilu
>
> Update mailroom with file writing.
> Goal: Write a full set of letters to all donors to individual files on
> disk.
>
> Where is this accomplished?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UWPCE-PythonCert-ClassRepos/Python210_Fall2019/pull/34?email_source=notifications&email_token=AJROS5DMYGC7276L3DPND3LQSH47BA5CNFSM4JI5MFN2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCKNELDA#pullrequestreview-312100236>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJROS5HSHCUJWVTC2SSY7RTQSH47BANCNFSM4JI5MFNQ>
> .
>

2019-11-07 02:26 UTC, majstorpoki approved these changes

2019-11-07 02:27 UTC, merged